server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # URL ???? ???? ??

      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka