server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: apiGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/oauth/jwks
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: review
              uri: lb://review
              predicates:
                - Path=/review/**
              filters:
                - StripPrefix=1
            - id: store
              uri: lb://store
              predicates:
                - Path=/store/**
              filters:
                - StripPrefix=1
            - id: order
              uri: lb://order
              predicates:
                - Path=/order/**
            - id: payment
              uri: lb://payment
              predicates:
                - Path=/payment/**
              filters:
                - StripPrefix=1
            - id: ai
              uri: lb://ai
              predicates:
                - Path=/ai/**
              filters:
                - StripPrefix=1
            - id: user
              uri: lb://user
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: mcp-server
              uri: lb://mcp-server
              predicates:
                - Path=/mcp-server/**
              filters:
                - StripPrefix=1
springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: store
        url: /store/v3/api-docs
      - name: review
        url: /review/v3/api-docs
      - name: order
        url: /order/v3/api-docs
      - name: payment
        url: /payment/v3/api-docs
      - name: ai
        url: /ai/v3/api-docs
      - name: user
        url: /user/v3/api-docs
      - name: auth
        url: /auth/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


auth:
  internal-token:
    url: http://localhost:8083/oauth2/token

